travis:
  secure:
    BINSTAR_TOKEN: v4Z6kY9DEcIYgO36qaRzwVXMbQYN/+molb63M2qNBsaPnAT6onKLgwaNKU41FhuStf9b39ie+CBxB8gbzPhMKI+nduJo45drrBVdM7ukSZ4DPIKoGf/iKRtWR97CX7+tGmBiQnaf4seBGdZVWPfer9z1KSSjTOyWmXohcEq+6ew2XrPYixobeOigBvOW18NJmSmw+e8TFX+ZIJC+66u1TRipNHFsJn7+dZ6zGgbLgXPVl5aq3p/kSS1+PCh4QbAzo3LcxoFS3OHMrDFE1diWUjO9romuRa8BrzvDFU+V9UOZrguTqRUM9Pd4BzyTWo468N7wakp3ogjg/XLccDnvPvY7ebNX2nPhllGYzPW/cm3D2Wj5WRzstZCzpH9yBZL+OTQZND3G7K0lWARTm3nZcetckT03NPEcIX1kf1Xkf8DVR6c1nfjrxhFBtS7vycojRj3tL9Ms7RXlo6aU3uTtHNXt4QcHMZY28EQpXuzurpKqBQc6lE6U6pfxYKWY8V68sjPD69Sn8w3EXoQJW2KOyWkPGERhPP0ZbhNyFSrJqaOtt7oqiux35/Pv2W0fjl5tl2z0/qzREokp23QPoVAYIRQgJt8OAsBbTM8mBzhPXsCHNSpWZKXpI8y7zubKFzZlTjn2SXK6bZmb0vYVoqp2vWIDu7gFIqZYirB9v012yzY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
